package es.storeapp.common;


public class Constants {

    private Constants() {
    }
    
    /* Messages */
    
    public static final String AUTH_INVALID_USER_MESSAGE = "auth.invalid.user";
    public static final String AUTH_INVALID_PASSWORD_MESSAGE = "auth.invalid.password";
    public static final String AUTH_INVALID_TOKEN_MESSAGE = "auth.invalid.token";
    public static final String REGISTRATION_INVALID_PARAMS_MESSAGE = "registration.invalid.parameters";
    public static final String UPDATE_PROFILE_INVALID_PARAMS_MESSAGE = "update.profile.invalid.parameters";
    public static final String CHANGE_PASSWORD_INVALID_PARAMS_MESSAGE = "change.password.invalid.parameters";
    public static final String RESET_PASSWORD_INVALID_PARAMS_MESSAGE = "reset.password.invalid.parameters";
    public static final String LOGIN_INVALID_PARAMS_MESSAGE = "login.invalid.parameters";
    public static final String INSTANCE_NOT_FOUND_MESSAGE = "instance.not.found.exception";
    public static final String DUPLICATED_INSTANCE_MESSAGE = "duplicated.instance.exception";
    public static final String DUPLICATED_COMMENT_MESSAGE = "duplicated.comment.exception";
    public static final String INVALID_PROFILE_IMAGE_MESSAGE = "invalid.profile.image";
    public static final String INVALID_STATE_EXCEPTION_MESSAGE = "invalid.state";
    public static final String INVALID_EMAIL_MESSAGE = "invalid.email";
   
    public static final String PRODUCT_ADDED_TO_THE_SHOPPING_CART = "product.added.to.the.cart";
    public static final String PRODUCT_REMOVED_FROM_THE_SHOPPING_CART = "product.removed.from.the.cart";
    public static final String PRODUCT_ALREADY_IN_SHOPPING_CART = "product.already.in.cart";
    public static final String PRODUCT_NOT_IN_SHOPPING_CART = "product.not.in.cart";
    public static final String EMPTY_SHOPPING_CART = "shopping.cart.empty";
    public static final String PRODUCT_COMMENT_CREATED = "product.comment.created";
    
    public static final String ORDER_AUTOGENERATED_NAME = "order.name.autogenerated";
    public static final String ORDER_SINGLE_PRODUCT_AUTOGENERATED_NAME_MESSAGE = "order.name.single.product.autogenerated";
    public static final String CREATE_ORDER_INVALID_PARAMS_MESSAGE = "create.order.invalid.parameters";
    public static final String PAY_ORDER_INVALID_PARAMS_MESSAGE = "pay.order.invalid.parameters";
    public static final String CANCEL_ORDER_INVALID_PARAMS_MESSAGE = "cancel.order.invalid.parameters";
    
    public static final String ORDER_CREATED_MESSAGE = "order.created";
    public static final String ORDER_PAYMENT_COMPLETE_MESSAGE = "order.payment.completed";
    public static final String ORDER_CANCEL_COMPLETE_MESSAGE = "order.cancellation.completed";
    
    public static final String REGISTRATION_SUCCESS_MESSAGE = "registration.success";
    public static final String PROFILE_UPDATE_SUCCESS = "profile.updated.success";
    public static final String CHANGE_PASSWORD_SUCCESS = "change.password.success";
    
    public static final String MAIL_SUBJECT_MESSAGE = "mail.subject";
    public static final String MAIL_TEMPLATE_MESSAGE = "mail.template";
    public static final String MAIL_HTML_NOT_SUPPORTED_MESSAGE = "mail.html.not.supported";
    public static final String MAIL_SUCCESS_MESSAGE = "mail.sent.success";
    public static final String MAIL_NOT_CONFIGURED_MESSAGE = "mail.not.configured";
    
    /* Web Endpoints */
    
    public static final String ROOT_ENDPOINT = "/";
    public static final String ALL_ENDPOINTS = "/**";
    public static final String LOGIN_ENDPOINT = "/login";
    public static final String LOGOUT_ENDPOINT = "/logout";
    public static final String USER_PROFILE_ALL_ENDPOINTS = "/profile/**";
    public static final String USER_PROFILE_ENDPOINT = "/profile";
    public static final String USER_PROFILE_IMAGE_ENDPOINT = "/profile/image";
    public static final String USER_PROFILE_IMAGE_REMOVE_ENDPOINT = "/profile/image/remove";
    public static final String REGISTRATION_ENDPOINT = "/registration";
    public static final String ORDERS_ALL_ENDPOINTS = "/orders/**";
    public static final String ORDERS_ENDPOINT = "/orders";
    public static final String ORDER_ENDPOINT = "/orders/{id}";
    public static final String ORDER_ENDPOINT_TEMPLATE = "/orders/{0}";
    public static final String ORDER_CONFIRM_ENDPOINT = "/orders/complete";
    public static final String ORDER_PAYMENT_ENDPOINT = "/orders/{id}/pay";
    public static final String ORDER_PAYMENT_ENDPOINT_TEMPLATE = "/orders/{0}/pay";
    public static final String ORDER_CANCEL_ENDPOINT = "/orders/{id}/cancel";
    public static final String PRODUCTS_ENDPOINT = "/products";
    public static final String PRODUCT_ENDPOINT = "/products/{id}";
    public static final String PRODUCT_TEMPLATE = "/products/{0}";
    public static final String CHANGE_PASSWORD_ENDPOINT = "/changePassword";
    public static final String RESET_PASSWORD_ENDPOINT = "/resetPassword";
    public static final String SEND_EMAIL_ENDPOINT = "/sendEmail";
    public static final String CART_ADD_PRODUCT_ENDPOINT = "/products/{id}/addToCart";
    public static final String CART_REMOVE_PRODUCT_ENDPOINT = "/products/{id}/removeFromCart";
    public static final String CART_ENDPOINT = "/cart";
    public static final String COMMENT_PRODUCT_ENDPOINT = "/products/{id}/rate";
    public static final String EXTERNAL_RESOURCES = "/resources/**";
    public static final String LIBS_RESOURCES = "/webjars/**";
    public static final String SEND_REDIRECT = "redirect:";
    
    /* Web Pages */
    
    public static final String LOGIN_PAGE = "Login";
    public static final String HOME_PAGE = "Index";
    public static final String ERROR_PAGE = "error";
    public static final String PASSWORD_PAGE = "ChangePassword";
    public static final String SEND_EMAIL_PAGE = "SendEmail";
    public static final String RESET_PASSWORD_PAGE = "ResetPassword";
    public static final String USER_PROFILE_PAGE = "Profile";
    public static final String PRODUCTS_PAGE = "Products";
    public static final String PRODUCT_PAGE = "Product";
    public static final String SHOPPING_CART_PAGE = "Cart";
    public static final String ORDER_COMPLETE_PAGE = "OrderConfirm";
    public static final String ORDER_PAGE = "Order";
    public static final String ORDER_PAYMENT_PAGE = "Payment";
    public static final String ORDERS_PAGE = "Orders";
    public static final String PAYMENTS_PAGE = "Orders";
    public static final String COMMENT_PAGE = "Comment";
    
    /* Request/session/model Attributes */
    
    public static final String PARAMS = "?";
    public static final String PARAM_VALUE = "=";
    public static final String NEW_PARAM_VALUE = "&";
    public static final String USER_SESSION = "user";
    public static final String SHOPPING_CART_SESSION = "shoppingCart";
    public static final String ERROR_MESSAGE = "errorMessage";
    public static final String EXCEPTION = "exception";
    public static final String WARNING_MESSAGE = "warningMessage";
    public static final String SUCCESS_MESSAGE = "successMessage";
    public static final String MESSAGE = "message"; /* predefined */
    public static final String LOGIN_FORM = "loginForm";
    public static final String USER_PROFILE_FORM = "userProfileForm";
    public static final String PASSWORD_FORM = "passwordForm";
    public static final String RESET_PASSWORD_FORM = "resetPasswordForm";
    public static final String COMMENT_FORM = "commentForm";
    public static final String PAYMENT_FORM = "paymentForm";
    public static final String NEXT_PAGE = "next";
    public static final String CATEGORIES = "categories";
    public static final String PRODUCTS = "products";
    public static final String PRODUCTS_ARRAY = "products[]";
    public static final String PRODUCT = "product";
    public static final String ORDER_FORM = "orderForm";
    public static final String ORDERS = "orders";
    public static final String ORDER = "order";
    public static final String PAY_NOW = "pay";
    public static final String BUY_BY_USER = "buyByUser";
    public static final String EMAIL_PARAM = "email";
    public static final String TOKEN_PARAM = "token";
    
    /* Entities, attributes and tables */
    
    public static final String USER_ENTITY = "User";
    public static final String PRODUCT_ENTITY = "Product";
    public static final String CATEGORY_ENTITY = "Category";
    public static final String COMMENT_ENTITY = "Comment";
    public static final String ORDER_ENTITY = "Order";
    public static final String ORDER_LINE_ENTITY = "OrderLine";
    
    public static final String USERS_TABLE = "Users";
    public static final String PRODUCTS_TABLE = "Products";
    public static final String CATEGORIES_TABLE = "Categories";
    public static final String COMMENTS_TABLE = "Comments";
    public static final String ORDERS_TABLE = "Orders";
    public static final String ORDER_LINES_TABLE = "OrderLines";
    
    public static final String PRICE_FIELD = "price";
    public static final String NAME_FIELD = "name";
    public static final String EMAIL_FIELD = "email";
    
    /* Other */
    
    public static final String CONTENT_TYPE_HEADER = "Content-Type";
    public static final String CONTENT_DISPOSITION_HEADER = "Content-Disposition";
    public static final String CONTENT_DISPOSITION_HEADER_VALUE = "attachment; filename={0}-{1}";
    public static final String PERSISTENT_USER_COOKIE = "user-info";
    public static final String URL_FORMAT = "{0}://{1}:{2}{3}{4}";
    
}
